x_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: translate_joint
    joint_speed: 2.0
    motor:
        id: 28
        init: 512
        min: 0
        max: 1023

theta_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rotate_joint
    joint_speed: 2.0
    motor:
        id: 16
        init: 512
        min: 0
        max: 1023
