// Generated by gencpp from file me212base/WheelVelCmd.msg
// DO NOT EDIT!


#ifndef ME212BASE_MESSAGE_WHEELVELCMD_H
#define ME212BASE_MESSAGE_WHEELVELCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me212base
{
template <class ContainerAllocator>
struct WheelVelCmd_
{
  typedef WheelVelCmd_<ContainerAllocator> Type;

  WheelVelCmd_()
    : desiredWV_R(0.0)
    , desiredWV_L(0.0)  {
    }
  WheelVelCmd_(const ContainerAllocator& _alloc)
    : desiredWV_R(0.0)
    , desiredWV_L(0.0)  {
  (void)_alloc;
    }



   typedef float _desiredWV_R_type;
  _desiredWV_R_type desiredWV_R;

   typedef float _desiredWV_L_type;
  _desiredWV_L_type desiredWV_L;




  typedef boost::shared_ptr< ::me212base::WheelVelCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me212base::WheelVelCmd_<ContainerAllocator> const> ConstPtr;

}; // struct WheelVelCmd_

typedef ::me212base::WheelVelCmd_<std::allocator<void> > WheelVelCmd;

typedef boost::shared_ptr< ::me212base::WheelVelCmd > WheelVelCmdPtr;
typedef boost::shared_ptr< ::me212base::WheelVelCmd const> WheelVelCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me212base::WheelVelCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me212base::WheelVelCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me212base

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'me212base': ['/home/robot/mit212project/catkin_ws/src/me212base/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me212base::WheelVelCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me212base::WheelVelCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me212base::WheelVelCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me212base::WheelVelCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me212base::WheelVelCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me212base::WheelVelCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me212base::WheelVelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "428fbbfd1f38717ca7baa73045b4efaa";
  }

  static const char* value(const ::me212base::WheelVelCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x428fbbfd1f38717cULL;
  static const uint64_t static_value2 = 0xa7baa73045b4efaaULL;
};

template<class ContainerAllocator>
struct DataType< ::me212base::WheelVelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me212base/WheelVelCmd";
  }

  static const char* value(const ::me212base::WheelVelCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me212base::WheelVelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 desiredWV_R\n\
float32 desiredWV_L\n\
";
  }

  static const char* value(const ::me212base::WheelVelCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me212base::WheelVelCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desiredWV_R);
      stream.next(m.desiredWV_L);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WheelVelCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me212base::WheelVelCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me212base::WheelVelCmd_<ContainerAllocator>& v)
  {
    s << indent << "desiredWV_R: ";
    Printer<float>::stream(s, indent + "  ", v.desiredWV_R);
    s << indent << "desiredWV_L: ";
    Printer<float>::stream(s, indent + "  ", v.desiredWV_L);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME212BASE_MESSAGE_WHEELVELCMD_H
